### ISSUE TITLE
blueprint-show with --cfn doesn't do anything

### ISSUE THREAD

**Issue by chanceymathews** [devstructure/blueprint#114]
I've been trying to get Blueprint to create a CloudFormation template but it's either not working or I'm missing a step. Here's what I try on a fresh EC2 instance using Amazon Linux: 

```
$ sudo blueprint create test
# [blueprint] using cached blueprintignore(5) rules
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for Yum packages
# [blueprint] searching for Python packages
# [blueprint] searching for configuration files
# [blueprint] searching for Ruby gems
# [blueprint] searching for npm packages
# [blueprint] searching for APT packages
# [blueprint] searching for software built from source
# [blueprint] searching for service dependencies
$ sudo blueprint show test --cfn
```

But nothing is displayed and no file is created. It's possible I'm missing some dependency but I don't know what that dependency is.

(Also, sorry if this is the wrong place to post this.)

**Comment by rcrowley** [comment]
This is a perfectly appropriate place to post this!

I'm unable to reproduce the issue - are you on a strange platform?  The `--cfn` option doesn't require any extra dependencies but it's possible the template it uses wasn't installed.  Does `$PYTHONPATH/blueprint/frontend/cfn.json` exist, where `$PYTHONPATH` is something like `/usr/lib/python2.7/dist-packages`?

**Comment by chanceymathews** [comment]
Sorry for the slow reply! My configuration is nothing special, just Amazon Linux with Git 1.7 and Blueprint 3.4 installed. I installed Blueprint using PIP.

I checked and $PYTHONPATH isn't set. Should it be? When I look in /usr/lib/python2.6/site-packages/blueprint/frontend I see a cfn.py but no cfn.json. I also searched the whole disk for cfn.json but nothing was found. :-( 

Did I miss a step or install the wrong version? 

Thanks for your help!

**Comment by chanceymathews** [comment]
Looks like PyPI/PIP doesn't install it correctly. I just installed with the source from Git (the v3.4.0 tag) and it works fine!

**Comment by rcrowley** [comment]
Looks like I need to specify `data_files` in the `setup.py` like Django does: https://code.djangoproject.com/browser/django/trunk/setup.py#L81.

**Comment by rcrowley** [comment]
@foofy This has been fixed and Blueprint 3.4.1 released to address it.  Thanks!

**Comment by mjschultz** [comment]
I just installed blueprint 3.4.2 via pip and this problem still exists. Looking at the source bundle from pypi, the cfn.json file is still missing.

After (too much) digging, [Code Kills](http://blog.codekills.net/2011/07/15/lies,-more-lies-and-python-packaging-documentation-on--package_data-/) indicates that the documentation regarding `sdist` and `package_data` is a lie. I'll be attaching a pull request that moves `cfn.json` into `MANIFEST.in` for the pypi distribution in a second.
